// Area (km2) dos 306 concelhos de Portugal com nome unico a nivel nacional
// (2026-09-18, a pedido - "quero uma formula que tenha como minas minimas 10
// de cada, mas dependendo do tamanho do concelho, esse numero aumenta").
// Fonte: tabela oficial (INE/DGT) replicada na Wikipedia, "List of
// municipalities of Portugal" (tabela de 308 municipios, area em km2).
//
// Chave = nome do concelho NORMALIZADO (normalizeConcelhoName(), js/resources.js
// - minusculas, sem acentos) para casar com o `concelho.name` que vem do
// Nominatim (js/hexes.js, resolveRegionAt) sem depender de acentuacao exata.
//
// Dois nomes sao duplicados a nivel nacional e ficam de fora do mapa (so um
// concelho por nome, o resto usa MINES_PER_RESOURCE_MIN como omissao -
// ver minasPorRecursoParaConcelho() em js/resources.js):
//   - "Lagoa" existe no Algarve (Faro, 88.3 km2) E nos Acores - fica so o
//     de Faro, mais provavel de ter jogadores.
//   - "Calheta" existe na Madeira (110.3 km2) E nos Acores - fica so o da
//     Madeira, pela mesma razao.
const CONCELHO_AREA_KM2 = {
  "abrantes": 714.7, // Abrantes (Santarém)
  "agueda": 335.3, // Águeda (Aveiro)
  "aguiar da beira": 206.9, // Aguiar da Beira (Guarda)
  "alandroal": 542.7, // Alandroal (Évora)
  "albergaria-a-velha": 155.4, // Albergaria-a-Velha (Aveiro)
  "albufeira": 140.6, // Albufeira (Faro)
  "alcacer do sal": 1465.3, // Alcácer do Sal (Setúbal)
  "alcanena": 127.3, // Alcanena (Santarém)
  "alcobaca": 408.1, // Alcobaça (Leiria)
  "alcochete": 128.4, // Alcochete (Setúbal)
  "alcoutim": 575.3, // Alcoutim (Faro)
  "alenquer": 304.2, // Alenquer (Lisboa)
  "alfandega da fe": 322, // Alfândega da Fé (Bragança)
  "alijo": 297.6, // Alijó (Vila Real)
  "aljezur": 323.5, // Aljezur (Faro)
  "aljustrel": 458.3, // Aljustrel (Beja)
  "almada": 70.2, // Almada (Setúbal)
  "almeida": 518, // Almeida (Guarda)
  "almeirim": 222.1, // Almeirim (Santarém)
  "almodovar": 777.9, // Almodôvar (Beja)
  "alpiarca": 95.4, // Alpiarça (Santarém)
  "alter do chao": 362, // Alter do Chão (Portalegre)
  "alvaiazere": 160.5, // Alvaiázere (Leiria)
  "alvito": 264.8, // Alvito (Beja)
  "amadora": 23.8, // Amadora (Lisboa)
  "amarante": 301.5, // Amarante (Porto)
  "amares": 82, // Amares (Braga)
  "anadia": 216.6, // Anadia (Aveiro)
  "angra do heroismo": 239, // Angra do Heroísmo (Azores)
  "ansiao": 176.2, // Ansião (Leiria)
  "arcos de valdevez": 447.6, // Arcos de Valdevez (Viana do Castelo)
  "arganil": 332.8, // Arganil (Coimbra)
  "armamar": 117.2, // Armamar (Viseu)
  "arouca": 329.1, // Arouca (Aveiro)
  "arraiolos": 683.8, // Arraiolos (Évora)
  "arronches": 314.8, // Arronches (Portalegre)
  "arruda dos vinhos": 78, // Arruda dos Vinhos (Lisboa)
  "aveiro": 199.9, // Aveiro (Aveiro)
  "avis": 606, // Avis (Portalegre)
  "azambuja": 262.7, // Azambuja (Lisboa)
  "baiao": 174.5, // Baião (Porto)
  "barcelos": 378.9, // Barcelos (Braga)
  "barrancos": 168.3, // Barrancos (Beja)
  "barreiro": 31.8, // Barreiro (Setúbal)
  "batalha": 103.3, // Batalha (Leiria)
  "beja": 1147.1, // Beja (Beja)
  "belmonte": 118.8, // Belmonte (Castelo Branco)
  "benavente": 521.5, // Benavente (Santarém)
  "bombarral": 91.3, // Bombarral (Leiria)
  "borba": 145.2, // Borba (Évora)
  "boticas": 322, // Boticas (Vila Real)
  "braga": 183.2, // Braga (Braga)
  "braganca": 1173.6, // Bragança (Bragança)
  "cabeceiras de basto": 241.8, // Cabeceiras de Basto (Braga)
  "cadaval": 174.9, // Cadaval (Lisboa)
  "caldas da rainha": 255.7, // Caldas da Rainha (Leiria)
  "calheta": 110.3, // Calheta (Madeira) - ver nota no topo do ficheiro
  "camara de lobos": 52.6, // Câmara de Lobos (Madeira)
  "caminha": 137.4, // Caminha (Viana do Castelo)
  "campo maior": 247, // Campo Maior (Portalegre)
  "cantanhede": 390.9, // Cantanhede (Coimbra)
  "carrazeda de ansiaes": 279.3, // Carrazeda de Ansiães (Bragança)
  "carregal do sal": 116.9, // Carregal do Sal (Viseu)
  "cartaxo": 158.2, // Cartaxo (Santarém)
  "cascais": 97.4, // Cascais (Lisboa)
  "castanheira de pera": 66.8, // Castanheira de Pera (Leiria)
  "castelo branco": 1438.2, // Castelo Branco (Castelo Branco)
  "castelo de paiva": 115, // Castelo de Paiva (Aveiro)
  "castelo de vide": 264.9, // Castelo de Vide (Portalegre)
  "castro daire": 379.1, // Castro Daire (Viseu)
  "castro marim": 300.9, // Castro Marim (Faro)
  "castro verde": 569.4, // Castro Verde (Beja)
  "celorico da beira": 247.2, // Celorico da Beira (Guarda)
  "celorico de basto": 181.1, // Celorico de Basto (Braga)
  "chamusca": 746, // Chamusca (Santarém)
  "chaves": 591.3, // Chaves (Vila Real)
  "cinfaes": 239.3, // Cinfães (Viseu)
  "coimbra": 319.4, // Coimbra (Coimbra)
  "condeixa-a-nova": 138.7, // Condeixa-a-Nova (Coimbra)
  "constancia": 80.4, // Constância (Santarém)
  "coruche": 1117.6, // Coruche (Santarém)
  "corvo": 17.1, // Corvo (Azores)
  "covilha": 555.6, // Covilhã (Castelo Branco)
  "crato": 398, // Crato (Portalegre)
  "cuba": 172.1, // Cuba (Beja)
  "elvas": 631.3, // Elvas (Portalegre)
  "entroncamento": 13.7, // Entroncamento (Santarém)
  "espinho": 21.1, // Espinho (Aveiro)
  "esposende": 95.4, // Esposende (Braga)
  "estarreja": 108.4, // Estarreja (Aveiro)
  "estremoz": 513.8, // Estremoz (Évora)
  "evora": 1307, // Évora (Évora)
  "fafe": 219.1, // Fafe (Braga)
  "faro": 201.6, // Faro (Faro)
  "felgueiras": 115.7, // Felgueiras (Porto)
  "ferreira do alentejo": 648.4, // Ferreira do Alentejo (Beja)
  "ferreira do zezere": 190.4, // Ferreira do Zêzere (Santarém)
  "figueira da foz": 379.1, // Figueira da Foz (Coimbra)
  "figueira de castelo rodrigo": 508.6, // Figueira de Castelo Rodrigo (Guarda)
  "figueiro dos vinhos": 173.4, // Figueiró dos Vinhos (Leiria)
  "fornos de algodres": 131.5, // Fornos de Algodres (Guarda)
  "freixo de espada a cinta": 244, // Freixo de Espada à Cinta (Bragança)
  "fronteira": 248.6, // Fronteira (Portalegre)
  "funchal": 75.7, // Funchal (Madeira)
  "fundao": 700.1, // Fundão (Castelo Branco)
  "gaviao": 294.6, // Gavião (Portalegre)
  "gois": 262.3, // Góis (Coimbra)
  "golega": 76.6, // Golegã (Santarém)
  "gondomar": 131.9, // Gondomar (Porto)
  "gouveia": 300.6, // Gouveia (Guarda)
  "grandola": 807.5, // Grândola (Setúbal)
  "guarda": 712.1, // Guarda (Guarda)
  "guimaraes": 241.3, // Guimarães (Braga)
  "horta": 173.1, // Horta (Azores)
  "idanha-a-nova": 1416.4, // Idanha-a-Nova (Castelo Branco)
  "ilhavo": 73.5, // Ílhavo (Aveiro)
  "lagoa": 88.3, // Lagoa (Faro) - ver nota no topo do ficheiro
  "lagos": 212.8, // Lagos (Faro)
  "lajes das flores": 70.1, // Lajes das Flores (Azores)
  "lajes do pico": 155.3, // Lajes do Pico (Azores)
  "lamego": 165.4, // Lamego (Viseu)
  "leiria": 565.6, // Leiria (Leiria)
  "lisboa": 84.8, // Lisboa (Lisboa)
  "loule": 764.2, // Loulé (Faro)
  "loures": 169.3, // Loures (Lisboa)
  "lourinha": 147.2, // Lourinhã (Lisboa)
  "lousa": 138.4, // Lousã (Coimbra)
  "lousada": 96, // Lousada (Porto)
  "macao": 400, // Mação (Santarém)
  "macedo de cavaleiros": 699.2, // Macedo de Cavaleiros (Bragança)
  "machico": 67.6, // Machico (Madeira)
  "madalena": 147.1, // Madalena (Azores)
  "mafra": 291.7, // Mafra (Lisboa)
  "maia": 83.1, // Maia (Porto)
  "mangualde": 219.3, // Mangualde (Viseu)
  "manteigas": 122, // Manteigas (Guarda)
  "marco de canaveses": 201.9, // Marco de Canaveses (Porto)
  "marinha grande": 187.1, // Marinha Grande (Leiria)
  "marvao": 154.9, // Marvão (Portalegre)
  "matosinhos": 62.2, // Matosinhos (Porto)
  "mealhada": 110.7, // Mealhada (Aveiro)
  "meda": 286.1, // Mêda (Guarda)
  "melgaco": 238.1, // Melgaço (Viana do Castelo)
  "mertola": 1292.8, // Mértola (Beja)
  "mesao frio": 26.7, // Mesão Frio (Vila Real)
  "mira": 124, // Mira (Coimbra)
  "miranda do corvo": 126.4, // Miranda do Corvo (Coimbra)
  "miranda do douro": 487.2, // Miranda do Douro (Bragança)
  "mirandela": 659, // Mirandela (Bragança)
  "mogadouro": 760.4, // Mogadouro (Bragança)
  "moimenta da beira": 220, // Moimenta da Beira (Viseu)
  "moita": 55.3, // Moita (Setúbal)
  "moncao": 211.3, // Monção (Viana do Castelo)
  "monchique": 395.3, // Monchique (Faro)
  "mondim de basto": 172.1, // Mondim de Basto (Vila Real)
  "monforte": 420.3, // Monforte (Portalegre)
  "montalegre": 805.8, // Montalegre (Vila Real)
  "montemor-o-novo": 1232.9, // Montemor-o-Novo (Évora)
  "montemor-o-velho": 229, // Montemor-o-Velho (Coimbra)
  "montijo": 348.1, // Montijo (Setúbal)
  "mora": 444, // Mora (Évora)
  "mortagua": 251.2, // Mortágua (Viseu)
  "moura": 958.4, // Moura (Beja)
  "mourao": 278.6, // Mourão (Évora)
  "murca": 189.4, // Murça (Vila Real)
  "murtosa": 73.3, // Murtosa (Aveiro)
  "nazare": 82.4, // Nazaré (Leiria)
  "nelas": 125.7, // Nelas (Viseu)
  "nisa": 575.8, // Nisa (Portalegre)
  "nordeste": 99.9, // Nordeste (Azores)
  "obidos": 141.6, // Óbidos (Leiria)
  "odemira": 1720.6, // Odemira (Beja)
  "odivelas": 26.4, // Odivelas (Lisboa)
  "oeiras": 45.7, // Oeiras (Lisboa)
  "oleiros": 471.1, // Oleiros (Castelo Branco)
  "olhao": 130.9, // Olhão (Faro)
  "oliveira de azemeis": 163.5, // Oliveira de Azeméis (Aveiro)
  "oliveira de frades": 145.4, // Oliveira de Frades (Viseu)
  "oliveira do bairro": 87.3, // Oliveira do Bairro (Aveiro)
  "oliveira do hospital": 234.5, // Oliveira do Hospital (Coimbra)
  "ourem": 416.6, // Ourém (Santarém)
  "ourique": 663.4, // Ourique (Beja)
  "ovar": 147.4, // Ovar (Aveiro)
  "pacos de ferreira": 71, // Paços de Ferreira (Porto)
  "palmela": 462.9, // Palmela (Setúbal)
  "pampilhosa da serra": 396.5, // Pampilhosa da Serra (Coimbra)
  "paredes": 156.8, // Paredes (Porto)
  "paredes de coura": 138.2, // Paredes de Coura (Viana do Castelo)
  "pedrogao grande": 128.8, // Pedrógão Grande (Leiria)
  "penacova": 216.7, // Penacova (Coimbra)
  "penafiel": 212.3, // Penafiel (Porto)
  "penalva do castelo": 134.2, // Penalva do Castelo (Viseu)
  "penamacor": 563.9, // Penamacor (Castelo Branco)
  "penedono": 133.7, // Penedono (Viseu)
  "penela": 134.8, // Penela (Coimbra)
  "peniche": 77.6, // Peniche (Leiria)
  "peso da regua": 94.9, // Peso da Régua (Vila Real)
  "pinhel": 484.5, // Pinhel (Guarda)
  "pombal": 626.1, // Pombal (Leiria)
  "ponta delgada": 233, // Ponta Delgada (Azores)
  "ponta do sol": 46.8, // Ponta do Sol (Madeira)
  "ponte da barca": 182.2, // Ponte da Barca (Viana do Castelo)
  "ponte de lima": 320.3, // Ponte de Lima (Viana do Castelo)
  "ponte de sor": 839.7, // Ponte de Sor (Portalegre)
  "portalegre": 447.1, // Portalegre (Portalegre)
  "portel": 601.2, // Portel (Évora)
  "portimao": 182.1, // Portimão (Faro)
  "porto": 41.3, // Porto (Porto)
  "porto de mos": 261.6, // Porto de Mós (Leiria)
  "porto moniz": 82.6, // Porto Moniz (Madeira)
  "porto santo": 42.4, // Porto Santo (Madeira)
  "povoa de lanhoso": 132.5, // Póvoa de Lanhoso (Braga)
  "povoa de varzim": 82.1, // Póvoa de Varzim (Porto)
  "povoacao": 108, // Povoação (Azores)
  "praia da vitoria": 161.3, // Praia da Vitória (Azores)
  "proenca-a-nova": 395.3, // Proença-a-Nova (Castelo Branco)
  "redondo": 365.5, // Redondo (Évora)
  "reguengos de monsaraz": 463.8, // Reguengos de Monsaraz (Évora)
  "resende": 123.4, // Resende (Viseu)
  "ribeira brava": 64.9, // Ribeira Brava (Madeira)
  "ribeira de pena": 217.5, // Ribeira de Pena (Vila Real)
  "ribeira grande": 180.2, // Ribeira Grande (Azores)
  "rio maior": 272.8, // Rio Maior (Santarém)
  "sabrosa": 156.9, // Sabrosa (Vila Real)
  "sabugal": 822.7, // Sabugal (Guarda)
  "salvaterra de magos": 242, // Salvaterra de Magos (Santarém)
  "santa comba dao": 112, // Santa Comba Dão (Viseu)
  "santa cruz": 68, // Santa Cruz (Madeira)
  "santa cruz da graciosa": 60.7, // Santa Cruz da Graciosa (Azores)
  "santa cruz das flores": 70.9, // Santa Cruz das Flores (Azores)
  "santa maria da feira": 215.1, // Santa Maria da Feira (Aveiro)
  "santa marta de penaguiao": 69.3, // Santa Marta de Penaguião (Vila Real)
  "santana": 136.3, // Santana (Madeira)
  "santarem": 560.3, // Santarém (Santarém)
  "santiago do cacem": 1059.8, // Santiago do Cacém (Setúbal)
  "santo tirso": 136.5, // Santo Tirso (Porto)
  "sao bras de alportel": 153.4, // São Brás de Alportel (Faro)
  "sao joao da madeira": 7.9, // São João da Madeira (Aveiro) - o mais pequeno do pais
  "sao joao da pesqueira": 266.1, // São João da Pesqueira (Viseu)
  "sao pedro do sul": 349, // São Pedro do Sul (Viseu)
  "sao roque do pico": 142.4, // São Roque do Pico (Azores)
  "sao vicente": 80.8, // São Vicente (Madeira)
  "sardoal": 92.2, // Sardoal (Santarém)
  "satao": 201.9, // Sátão (Viseu)
  "seia": 435.7, // Seia (Guarda)
  "seixal": 95.5, // Seixal (Setúbal)
  "sernancelhe": 228.6, // Sernancelhe (Viseu)
  "serpa": 1104, // Serpa (Beja)
  "serta": 446.7, // Sertã (Castelo Branco)
  "sesimbra": 195, // Sesimbra (Setúbal)
  "setubal": 171.9, // Setúbal (Setúbal)
  "sever do vouga": 129.6, // Sever do Vouga (Aveiro)
  "silves": 680, // Silves (Faro)
  "sines": 202.6, // Sines (Setúbal)
  "sintra": 319.2, // Sintra (Lisboa)
  "sobral de monte agraco": 52.1, // Sobral de Monte Agraço (Lisboa)
  "soure": 265.1, // Soure (Coimbra)
  "sousel": 279.4, // Sousel (Portalegre)
  "tabua": 199.8, // Tábua (Coimbra)
  "tabuaco": 133.9, // Tabuaço (Viseu)
  "tarouca": 100.1, // Tarouca (Viseu)
  "tavira": 607, // Tavira (Faro)
  "terras de bouro": 277.5, // Terras de Bouro (Braga)
  "tomar": 351.2, // Tomar (Santarém)
  "tondela": 371.2, // Tondela (Viseu)
  "torre de moncorvo": 531.6, // Torre de Moncorvo (Bragança)
  "torres novas": 270, // Torres Novas (Santarém)
  "torres vedras": 407.1, // Torres Vedras (Lisboa)
  "trancoso": 361.5, // Trancoso (Guarda)
  "trofa": 71.9, // Trofa (Porto)
  "vagos": 169.9, // Vagos (Aveiro)
  "vale de cambra": 146.5, // Vale de Cambra (Aveiro)
  "valenca": 117.1, // Valença (Viana do Castelo)
  "valongo": 75.1, // Valongo (Porto)
  "valpacos": 548.8, // Valpaços (Vila Real)
  "velas": 117.4, // Velas (Azores)
  "vendas novas": 222.4, // Vendas Novas (Évora)
  "viana do alentejo": 393.6, // Viana do Alentejo (Évora)
  "viana do castelo": 318.6, // Viana do Castelo (Viana do Castelo)
  "vidigueira": 316, // Vidigueira (Beja)
  "vieira do minho": 218.5, // Vieira do Minho (Braga)
  "vila de rei": 191.3, // Vila de Rei (Castelo Branco)
  "vila do bispo": 179, // Vila do Bispo (Faro)
  "vila do conde": 149, // Vila do Conde (Porto)
  "vila do porto": 96.9, // Vila do Porto (Azores)
  "vila flor": 265.8, // Vila Flor (Bragança)
  "vila franca de xira": 317.7, // Vila Franca de Xira (Lisboa)
  "vila franca do campo": 78, // Vila Franca do Campo (Azores)
  "vila nova da barquinha": 49.6, // Vila Nova da Barquinha (Santarém)
  "vila nova de cerveira": 108.6, // Vila Nova de Cerveira (Viana do Castelo)
  "vila nova de famalicao": 201.7, // Vila Nova de Famalicão (Braga)
  "vila nova de foz coa": 398.2, // Vila Nova de Foz Côa (Guarda)
  "vila nova de gaia": 168.7, // Vila Nova de Gaia (Porto)
  "vila nova de paiva": 175.5, // Vila Nova de Paiva (Viseu)
  "vila nova de poiares": 84.5, // Vila Nova de Poiares (Coimbra)
  "vila pouca de aguiar": 437.1, // Vila Pouca de Aguiar (Vila Real)
  "vila real": 378.8, // Vila Real (Vila Real)
  "vila real de santo antonio": 60.9, // Vila Real de Santo António (Faro)
  "vila velha de rodao": 329.9, // Vila Velha de Ródão (Castelo Branco)
  "vila verde": 228.7, // Vila Verde (Braga)
  "vila vicosa": 194.9, // Vila Viçosa (Évora)
  "vimioso": 481.6, // Vimioso (Bragança)
  "vinhais": 694.9, // Vinhais (Bragança)
  "viseu": 507.1, // Viseu (Viseu)
  "vizela": 24.7, // Vizela (Braga)
  "vouzela": 193.7, // Vouzela (Viseu)
};

// Menor concelho do pais (Sao Joao da Madeira) - ancora da formula em
// minasPorRecursoParaConcelho() (js/resources.js): e o unico concelho que
// fica garantidamente com o minimo de minas.
const MINA_AREA_REFERENCIA_KM2 = CONCELHO_AREA_KM2["sao joao da madeira"];
